[package]
name = "oxidrive"
version = "0.1.0"
edition = "2024"

[dependencies]
lzma-sdk-sys = { version = "0.1.1+24.09", default-features = false }
zip = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
reqwest = { version = "0.12.23", features = ["json", "stream"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "fs"] }
futures-util = "0.3.31"
anyhow = "1.0.100"
async-trait = "0.1.89"
sysinfo = "0.37.2"
regex = "1.12.2"
#log = "0.4.28"
#env_logger = "0.11.8"
quick-xml = "0.38.3"
globset = "0.4.18"
thiserror = "2.0.17"
rayon = "1.11.0"
pathdiff = "0.2.3"
lazy_static = "1.5.0"
tempfile = "3.23.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.3"
objc2-foundation = { version = "0.3.2", features = ["NSFileManager", "NSString", "NSURL", "NSPathUtilities"] }
objc2-app-kit = "0.3.2"
core-foundation = "0.10.1"
core-foundation-sys = "0.8.7"
libc = "0.2.177"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = ["Win32_UI_Shell", "Win32_System_Com"] }
