[package]
name = "oxidrive"
version = "0.1.0"
edition = "2024"

[dependencies]
lzma-sdk-sys = "0.1.1+24.09"
zip = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
reqwest = { version = "0.12.23", features = ["json", "stream"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "fs"] }
futures-util = "0.3.31"
anyhow = "1.0.100"
async-trait = "0.1.89"
sysinfo = "0.37.2"
serde-xml-rs = "0.8.1"
regex = "1.12.2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.3"
objc2-foundation = { version = "0.3.2", features = ["NSFileManager", "NSString", "NSURL", "NSPathUtilities"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = ["Win32_UI_Shell", "Win32_System_Com"] }